### ISSUE TITLE
Return NaN when query bitcoin balance for a long time.

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#104]
**Describe the bug**
The result returns really slow for some reason, and it will influence other address.
![截屏2020-12-31 下午8 29 50](https://user-images.githubusercontent.com/37820916/103410591-00349600-4ba7-11eb-816c-9f62622ab2e6.png)
We should make it more quick to show although there will be some address cannot receive the result.

**Expected behavior**
Set a quick timeout for list query, if not response. Show NaN or other string in the list.

**Comment by SherLzp** [comment]
fixed by #108
