### ISSUE TITLE
Add auth verification rpc api between Mining-Bot and Mining-Local-Server

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#109]
**Is your feature request related to a problem? Please describe.**
- Support Mining_local_server VPS
- Using AES256 to encrypt seed

**Describe the solution you'd like**
Before sending encrypted seed, call this rpc api to check the password generated by Mining-Local-Server when setting up.

**Comment by SherLzp** [comment]
fixed by #114
