### ISSUE TITLE
Mining Module Modification

### ISSUE THREAD

**Issue by SherLzp** [Daemon-Technologies/Mining-Bot#20]
**Is your feature request related to a problem? Please describe.**
In order to allow users to operate their own mining process more fine-grained and obtain more comprehensive mining-related information. We are considering the development of the following features.
Priority:
- Adjust the amount of bitcoin burned in each PoB cycle in stacks-blockchain dynamically #15 

- A rpc method that allows others to get miner selection info after each block mined

> currently the block info API only returns some info of transaction, doesn't contain info of consensus.

- A rpc method that allows others to get info of other miners #14 

**Describe the solution you'd like**
Right now, because of the missing APIs of stacks-blockchain https://github.com/blockstack/stacks-blockchain/issues/1969#issue-721253193. Left time is not enough for us to implement these features which are proposed in https://github.com/blockstack/stacks-blockchain/issues/1969#issuecomment-708517282 before Mining Competition. In order to allow users to use the Mining Bot we constructed before the Mining Competition, we choose to modify stacks-node(https://github.com/blockstack/stacks-blockchain/tree/master/testnet/stacks-node) first to implement mining features of stacks-blockchain. 

**Describe alternatives you've considered**

**Additional context**
Later, based on user feedback and stacks-blockchian development progress, we will follow up and modify Mining Module as a separate program. #18

**Comment by tyGavinZJU** [comment]
API Method Design Refer to this issue https://github.com/blockstack/stacks-blockchain/issues/970

**Comment by trancetr** [comment]
I get this problem

![image](https://user-images.githubusercontent.com/72358313/102932022-93d3db80-44b0-11eb-8b44-db32c78c8252.png)
when hit download button
![image](https://user-images.githubusercontent.com/72358313/102932107-ba921200-44b0-11eb-826c-c2d20fb79030.png)
Console  picture 

![image](https://user-images.githubusercontent.com/72358313/102932167-d0073c00-44b0-11eb-83f9-0b363a2b6690.png)

**Comment by SherLzp** [comment]
fixed by #113
