### ISSUE TITLE
Mining-Bot Client Documentation

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#21]
- Github Repo Readme
- Deploy and using Tutorial (if necessary)

**Comment by tyGavinZJU** [comment]
Instruction
- [stacks-node Binary Compile](https://docs.blockstack.org/stacks-blockchain/running-testnet-node)
- [Mining-local-server Launch](https://github.com/Daemon-Technologies/Mining-local-server)
- [Mining-Bot-Client Launch](https://github.com/Daemon-Technologies/miningbot-client)

Reference
- [stacks-blockchain github](https://github.com/blockstack/stacks-blockchain)

**Comment by tyGavinZJU** [comment]
Move to https://github.com/Daemon-Technologies/docs/issues/2

**Comment by tyGavinZJU** [comment]
Still needs to finish the README of Mining-Bot Repo

**Comment by whoabuddy** [comment]
Would it be easier to direct users to [download the latest release](https://github.com/blockstack/stacks-blockchain/releases/latest) versus compiling the binaries themselves? 

I've been testing this in a few pair mining sessions and it greatly reduces the technical debt of setting up a miner. On Mac I did have to approve an unidentified developer warning, which varied a bit by OS, but after that was done it was possible to run the file.

I'm not sure if later versions work with Krypton (they should, but I've been just using latest releases, not testing previous versions). This was the [last release I successfully used with Krypton](https://github.com/blockstack/stacks-blockchain/releases/tag/v23.0.0.12-krypton) before the launch of Xenon.

Also, this means the file would need to be put in the user's path variable via another method than using Rust, so this line would have to change: `cp target/release/stacks-node $HOME/.cargo/bin`

For Mac/Linux, I believe `/usr/bin` could work? Not sure on Windows as I haven't played much with wsl yet.

**Comment by tyGavinZJU** [comment]
> Would it be easier to direct users to [download the latest release](https://github.com/blockstack/stacks-blockchain/releases/latest) versus compiling the binaries themselves?
> 
> I've been testing this in a few pair mining sessions and it greatly reduces the technical debt of setting up a miner. On Mac I did have to approve an unidentified developer warning, which varied a bit by OS, but after that was done it was possible to run the file.
> 
> I'm not sure if later versions work with Krypton (they should, but I've been just using latest releases, not testing previous versions). This was the [last release I successfully used with Krypton](https://github.com/blockstack/stacks-blockchain/releases/tag/v23.0.0.12-krypton) before the launch of Xenon.
> 
> Also, this means the file would need to be put in the user's path variable via another method than using Rust, so this line would have to change: `cp target/release/stacks-node $HOME/.cargo/bin`
> 
> For Mac/Linux, I believe `/usr/bin` could work? Not sure on Windows as I haven't played much with wsl yet.

@whoabuddy 
I think these days before restart time, we could choose a best version and modify the documentation websites.

**Comment by tyGavinZJU** [comment]
Fixed by 1.0.0 tag release
