### ISSUE TITLE
Bitcoin Balance Reminder in Node-Start Form 

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#37]
**Describe the solution you'd like**
When Click the Start Mining Button, it will judge the balance of bitcoin address, when the balance less than 0.01, it will remind User to Recharge Bitcoin for certain address.

We should remind user to a certain address like (Faucet / bitcoin wallet)

**Comment by MONIMAKER365** [comment]
more easier if we do bitcoin wallet coz they might integrate multiple address on one recipient, i know what you can do thats why i trust you on this I'm still learning most possible easiest way in mining plus if they put the trust on your work it will open a big opportunity on your line of job

**Comment by tyGavinZJU** [comment]
> more easier if we do bitcoin wallet coz they might integrate multiple address on one recipient, i know what you can do thats why i trust you on this I'm still learning most possible easiest way in mining plus if they put the trust on your work it will open a big opportunity on your line of job

Thank you @MONIMAKER365, I add faucet notification in ea4ba06ff62e5632c2033f9bd2ab8a5d9cacc6c3. I will close this issue temporarily.

About the feature you mention if we should integrate bitcoin wallet, I have to say we have use bitcoin library to do that job. But from the design of Mining-Bot, I do think there is no need to integrate a bitcoin wallet. The future version of Mining-Bot should just work as a transaction signer, and could be connected with hardware wallet like trezor because maintain a bitcoin wallet is a tough work, we want to pay more attention about Mining Moduel.
