### ISSUE TITLE
Show Mining Info from block by block in Client Module

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#42]
**Is your feature request related to a problem? Please describe.**
By now, Mining info only includes Miner information in all. We need to show which miner mined certain block using what amount of bitcoin.

**Describe the solution you'd like**

Features as Follow:
Stacks Block list including 
- Who mined block N.
- How much Miner A burned in Block N

**Comment by MONIMAKER365** [comment]
how much miner a burned in block N

**Comment by tyGavinZJU** [comment]
Fixed by https://github.com/Daemon-Technologies/Mining-Monitor/issues/2#issuecomment-743710960
