### ISSUE TITLE
Highlight the Miner info list by client user

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#46]
**Is your feature request related to a problem? Please describe.**
You have to find your own bitcoin address in wallet module and search it in mining list module.
It should be highlighted.

**Describe the solution you'd like**
- modify the *get_node_status* api of Mining-Local-Server, if there is a node running, let it return the bitcoin address.
- show the miner info in mining status and highlight the miner info in Mining List.

**Comment by MONIMAKER365** [comment]
modify the get_node_status api of Mining-Local-Server, if there is a node running, let it return the bitcoin address.

**Comment by MONIMAKER365** [comment]
show the miner info in mining status and highlight the miner info in Mining List.

**Comment by tyGavinZJU** [comment]
Fixed in latest update
