### ISSUE TITLE
Runing Mining-Bot series in VPS for Mining 24/7

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#47]
**Is your feature request related to a problem? Please describe.**
https://forum.stacks.org/t/request-for-testing-alpha-mining-bot/11372/9
>Thank you for the suggestion. That is helpful for me. One more question is if I install the stacks-node in my computer, does that mean I have to leave my computer on 24/7 to mine STX? I really want to run the node on a VPS so I don’t have to keep turn on my computer 24hours a day.

**Describe the solution you'd like**
Add an rpc api in Mining-Local-Server named : *start node* / *stop node* / *get node status*
If the method exposed to public ip, it should have some authentication like *rsa encrypted*. The solution will include how to create a key for user and how to encrypt some message between Mining-Local-Server rpc api.

**Comment by doodlemania2** [comment]
+1 to this, wanting to run the client and server from a VPS and access it via web browser (or provide API commands to start up mining locally on the VPS)

**Comment by tyGavinZJU** [comment]
> +1 to this, wanting to run the client and server from a VPS and access it via web browser (or provide API commands to start up mining locally on the VPS)

The Mining-Bot is designed as a ui interface client-app. I think this work should be finished in Mining-Local-Server right?

**Comment by tyGavinZJU** [comment]
![Mining-Bot](https://user-images.githubusercontent.com/37820916/102067096-a194bb80-3e35-11eb-93f7-14c91133016d.png)

Feature to add up in Mining-Bot(left side):
- Symmetry Key set
- Symmetry Key reset Dialog
- ```getNodeStatus``` api add **message** segment
- ```startMining stopMining``` post body encrypted row by row (not include key only value)
- Client page load logic
- localstorage about password

**Comment by SherLzp** [comment]
fixed by #115
