### ISSUE TITLE
Testnet switch between Krypton and Xenon

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#54]
**Is your feature request related to a problem? Please describe.**
Testnet switch between Krypton and Xenon

**Describe the solution you'd like**
Add a switch button in the top right. Switch will influence:
- Public Module: chain status, block status endpoint
- Client Module: service api, monitor api, faucet api
- Wallet Module: balance end point

**Comment by whoabuddy** [comment]
Sharing this from Diwaker in the Stacks chat:

> Anyone wishing to interact with Krypton should use the following endpoints:

- miner: `krypton.blockstack.org`
- API: `stacks-node-api.krypton.blockstack.org`
- bitcoind: `bitcoind.krypton.blockstack.org`

**Comment by tyGavinZJU** [comment]
> Sharing this from Diwaker in the Stacks chat:
> 
> > Anyone wishing to interact with Krypton should use the following endpoints:
> 
> * miner: `krypton.blockstack.org`
> * API: `stacks-node-api.krypton.blockstack.org`
> * bitcoind: `bitcoind.krypton.blockstack.org`
> 
> This may help with #53 as well?

Yes, it is. The difficulty I met is too many service in Mining-Bot need to be switched between two testnets.

**Comment by SherLzp** [comment]
fixed by #115
