### ISSUE TITLE
locale warning missing en-US

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#55]
**Describe the bug**
![截屏2020-12-03 下午4 10 40](https://user-images.githubusercontent.com/37820916/100981760-2fdd8780-3582-11eb-8048-eedb0803c07e.png)

**Steps To Reproduce**
open **public data** page

**Expected behavior**
No red warning!

**Comment by SherLzp** [comment]
fixed by #66
