### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by joshmatix** [Daemon-Technologies/Mining-Bot#64]
https://daemon-technologies.github.io/docs/Mining-Bot-Alpha-Version/Build-Before-Using/Mining-Bot-Alpha-Tutorial-EN.html

The tutorial of installing Rust comes from **blockstack official document**. You can see it for more information.

https://docs.blockstack.org/stacks-blockchain/running-testnet-node  - "Page not found"

**Comment by tyGavinZJU** [comment]
Fixed by https://github.com/Daemon-Technologies/docs/pull/16 I think.
