### ISSUE TITLE
Issue installing Mining-Bot yarn install

### ISSUE THREAD

**Issue by tyGavinZJU** [Daemon-Technologies/Mining-Bot#67]
https://github.com/Daemon-Technologies/docs/issues/21#issue-765519394

> I have been trying to install and running the Mining-Bot on windows with Unix Ubuntu wsl. In chapter 3 of the documentation the yarn install command generates numerous warnings and then exits late in the process with the following error:
Register plugin /home/xxx/Mining-Bot/node_modules/umi-plugin-antd-icon-config/lib/index.js failed, since Cannot use import statement outside a module
Error: Register plugin /home/xxx/Mining-Bot/node_modules/umi-plugin-antd-icon-config/lib/index.js failed, since Cannot use import statement outside a module
at Object.apply (/home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:159:15)
at /home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/Service.js:348:22
at Generator.next ()
at asyncGeneratorStep (/home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/Service.js:108:103)
at _next (/home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/Service.js:110:194)
at /home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/Service.js:110:364
at new Promise ()
at /home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/Service.js:110:97
at Service.applyAPI (/home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/Service.js:355:7)
at /home/xxx/Mining-Bot/node_modules/@umijs/core/lib/Service/Service.js:438:20
error Command failed with exit code 1.

Any ideas?

**Comment by tyGavinZJU** [comment]
@KingGreyWulf

**Comment by tyGavinZJU** [comment]
![x8i3s-cy0sg](https://user-images.githubusercontent.com/37820916/102034836-f581af00-3df9-11eb-878f-222aba69fde1.gif)

Looks good to me, you can have a check.

**Comment by KingGreyWulf** [comment]
Thanks, it worked now. Must have installed incorrect

**Comment by tyGavinZJU** [comment]
Closed
