### ISSUE TITLE
No information about burn fee set to low.

### ISSUE THREAD

**Issue by LNow** [Daemon-Technologies/Mining-Bot#92]
**Describe the bug**
When burn fee is to low value, miner is throwing an error `Total burn fee not enough for number of outputs` but bot is not aware of it, therefore operator don't know something is wrong.

https://github.com/blockstack/stacks-blockchain/blob/1a34c15684419eca3b8234394c8aca186f7568ad/testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs#L764

**Steps To Reproduce**
Set burn fee to low value ie. 200 and run miner.

**Expected behavior**
If fee is to low to process tx, bot should display information about it.

**Comment by SherLzp** [comment]
fixed by #99
