### ISSUE TITLE
Stacks node download on rpi not correct executable

### ISSUE THREAD

**Issue by friedger** [Daemon-Technologies/Mining-Bot#94]
**Describe the bug**
On Raspberry Pi 3B, the downloaded executable of stacks-node does not start

**Steps To Reproduce**
On Raspberry Pi 3B, 
1. Start the bot with `yarn start`
2. Clicking the Download button
3. Try starting the stacks node
4. see error: `./stacks-node: cannot execute binary file: Exec format error`

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Raspian

**Additional context**
Workaround, download stacks-node (linux-armv7.zip) manually and unzip file

**Comment by tyGavinZJU** [comment]
> 4. see error: `./stacks-node: cannot execute binary file: Exec format error`

Could you share the ```os.platform()``` return result in nodejs?

**Comment by friedger** [comment]
The bot should check `os.arch()`. os.platform is `linux`

**Comment by tyGavinZJU** [comment]
> The bot should check `os.arch()`. os.platform is `linux`

What is the result of os.arch()? arm64 or arm?

**Comment by tyGavinZJU** [comment]
> The bot should check `os.arch()`. os.platform is `linux`

I didn't judge the CPU arch for each system. Can update it soon.

**Comment by friedger** [comment]
For rpi, arch returns `arm`

**Comment by tyGavinZJU** [comment]
fixed 14665daa2da3670b08be46ab658ba1c8165b03b3
