### ISSUE TITLE
User should have a possibility to pick which bitcoind node he want to use.

### ISSUE THREAD

**Issue by LNow** [Daemon-Technologies/Mining-Bot#98]
**Is your feature request related to a problem? Please describe.**
Official `bitcoind.krypton.blockstack.org` bitcoind server is overloaded and if someone want to use local one, have to manually edit `miner-Krypton.toml`.

**Describe the solution you'd like**
Miner bot interface should allow user to choose one bitcoind server from list of known and trusted bitcoind servers, or manually enter details of server user want to use (ie. local one).

When user decide to enter bitcoind server details manually, he should see following fields:

1. Hostname / IP address
2. RPC Port
3. Peer Port
4. RPC Username
5. RPC Password

Last two fields should be optional, as user might want to hide his bitcoind server behind some type of proxy ie. [bitcoin-neon-controller](https://github.com/blockstack/stacks-blockchain/tree/master/testnet/bitcoin-neon-controller)

**Describe alternatives you've considered**
User can manually edit `*.toml` file, but it is error prone.

**Additional context**
Choosing bitcoind server should be defined as 3rd step of bot set-up wizard.

In addition to that official, public bitcoind servers should be set up using [bitcoin-neon-controller](https://github.com/blockstack/stacks-blockchain/tree/master/testnet/bitcoin-neon-controller) as exposing RPC credentials to all users is a huge security risk.
Probably they should also be connected with each other.

**Comment by SherLzp** [comment]
fixed by #114
